#!/bin/sh -x

aclocal -I .

if libtoolize --copy --force
then
  dummy=dummy
else
  if glibtoolize --copy --force
  then
    set +x
    echo "bootstrap: Note: glibtoolize succeeded where libtoolize failed"
    set -x
  else
    exit 1
  fi
fi
autoconf

automake --foreign --add-missing --copy --include-deps
